repos:
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        args: [--line-length=110, --skip-string-normalization]

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--max-line-length=110, "--extend-ignore=E203,W503"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile=black, --line-length=110]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.941
    hooks:
      - id: mypy
